import { existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { chromium } from '@playwright/test';
import { runAuthSetup, runPlaywright, stagePlaywrightState } from '@xera-ai/web';
import { generateRunId, resolveArtifactPaths } from '../artifact/paths';
import { needsRefresh } from '../auth/refresh';
import { readAuthState } from '../auth/state';
import { loadConfig } from '../config/load';
import { acquireLock, forceUnlock, isLockStale, readLock, releaseLock } from '../lock/file-lock';
import { NdjsonLogger } from '../logging/ndjson-logger';

export async function execCmd(argv: string[]): Promise<number> {
  const ticket = argv[0];
  if (!ticket) {
    console.error('[xera:exec] usage: exec <TICKET>');
    return 1;
  }
  const grepIdx = argv.indexOf('--grep');
  const grep = grepIdx > -1 ? argv[grepIdx + 1] : undefined;
  const cwd = process.cwd();
  const config = await loadConfig(cwd);
  const paths = resolveArtifactPaths(cwd, ticket);
  const runId = generateRunId();
  const log = new NdjsonLogger(paths.logPath);

  // Acquire lock
  if (!acquireLock(paths.lockPath, runId)) {
    if (isLockStale(paths.lockPath)) {
      console.error(
        `[xera:exec] stale lock detected; force unlocking. Run \`xera-internal unlock ${ticket}\` to clear manually.`,
      );
      forceUnlock(paths.lockPath);
      acquireLock(paths.lockPath, runId);
    } else {
      const existing = readLock(paths.lockPath);
      console.error(
        `[xera:exec] another run in progress (PID ${existing?.pid} on ${existing?.hostname}, started ${existing?.started_at}). Wait or run \`xera-internal unlock ${ticket}\`.`,
      );
      return 1;
    }
  }

  const t0 = Date.now();
  try {
    if (!config.web) {
      throw new Error('web adapter requires web config block');
    }
    const webConfig = config.web;

    // Auth refresh per role declared in xera.config.ts
    if (webConfig.auth.strategy === 'storageState' && webConfig.auth.setupScript) {
      const browser = await chromium.launch();
      try {
        for (const [roleName, roleCreds] of Object.entries(webConfig.auth.roles)) {
          const entry = readAuthState(paths.authDir, roleName);
          if (
            needsRefresh(entry, {
              ttl: webConfig.auth.ttl,
              refreshBuffer: webConfig.auth.refreshBuffer,
            })
          ) {
            const email = process.env[roleCreds.envEmail];
            const password = process.env[roleCreds.envPassword];
            if (!email || !password) {
              console.error(
                `[xera:exec] missing env ${roleCreds.envEmail} or ${roleCreds.envPassword} for role "${roleName}"`,
              );
              return 1;
            }
            await runAuthSetup({
              role: roleName,
              creds: { email, password },
              setupScriptPath: join(cwd, webConfig.auth.setupScript),
              authDir: paths.authDir,
              browser,
            });
            log.log({ step: 'auth-refresh', role: roleName });
          }
        }
      } finally {
        await browser.close();
      }
    }

    // Stage Playwright storageState files at predictable paths
    // (.xera/.auth/.cache/<role>.json) — generated spec.ts references these
    // via test.use({ storageState }) when an authenticated session is needed.
    if (webConfig.auth.strategy === 'storageState') {
      for (const roleName of Object.keys(webConfig.auth.roles)) {
        if (readAuthState(paths.authDir, roleName)) {
          stagePlaywrightState(paths.authDir, roleName);
        }
      }
    }

    // Use the root playwright.config.ts (generated by `xera init`). We never
    // emit a per-ticket config — that path duplicates the root and bit-rots.
    const cfgPath = join(cwd, 'playwright.config.ts');
    if (!existsSync(cfgPath)) {
      console.error(
        `[xera:exec] missing ${cfgPath}. Run \`xera init\` to scaffold it, then re-run.`,
      );
      return 1;
    }

    const runDir = paths.runPath(runId).runDir;
    mkdirSync(runDir, { recursive: true });

    const envName = process.env.XERA_ENV ?? webConfig.defaultEnv;
    const baseURL = webConfig.baseUrl[envName] ?? webConfig.baseUrl[webConfig.defaultEnv]!;

    const reportJsonPath = join(runDir, 'report.json');

    log.log({ step: 'exec.start', runId, env: envName, baseURL });
    const r = await runPlaywright({
      specPath: paths.specPath,
      configPath: cfgPath,
      outputDir: runDir,
      env: {
        XERA_BASE_URL: baseURL,
        XERA_ENV: envName,
        // Playwright's JSON reporter prints to stdout by default. Redirect it
        // to a file inside the run dir so xera:normalize has a deterministic
        // path to read.
        PLAYWRIGHT_JSON_OUTPUT_NAME: reportJsonPath,
      },
      ...(grep && { grep }),
    });
    log.log({ step: 'exec.done', runId, exit: r.exitCode, ms: Date.now() - t0 });

    console.log(`[xera:exec] runId=${runId} outcome=${r.outcome}`);
    // Exit 3 means "test failed" (expected vs infra error)
    return r.outcome === 'PASS' ? 0 : 3;
  } finally {
    releaseLock(paths.lockPath);
  }
}
