import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { z } from 'zod';

const CATEGORY_ENUM = z.enum([
  'negative',
  'boundary',
  'state-combination',
  'race',
  'error-recovery',
  'a11y',
  'security-smell',
  'non-functional',
]);

const ProposalsSchema = z.object({
  proposals: z.array(
    z.object({
      id: z.string().min(1),
      ticketId: z.string().min(1),
      category: CATEGORY_ENUM,
      severity: z.enum(['low', 'medium', 'high']),
      title: z.string().min(1),
      rationale: z.string().min(1),
      gherkin: z.string().min(1),
    }),
  ),
});

type Proposals = z.infer<typeof ProposalsSchema>;
type Proposal = Proposals['proposals'][number];

interface ParsedArgs {
  ticket: string;
  accept: string;
}

function parseArgs(argv: string[]): ParsedArgs | { error: string } {
  let ticket: string | undefined;
  let accept: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--accept') {
      const v = argv[++i];
      if (v !== undefined) accept = v;
    } else if (a === '--help-stub') {
      /* no-op */
    } else if (a && !a.startsWith('--') && ticket === undefined) {
      ticket = a;
    } else {
      return { error: `unknown flag: ${a}` };
    }
  }
  if (!ticket) return { error: 'ticket key is required as a positional argument' };
  if (!accept)
    return { error: '--accept is required (comma-separated IDs, "all", or "high-only")' };
  return { ticket, accept };
}

function selectProposals(all: Proposal[], accept: string): Proposal[] | { error: string } {
  const trimmed = accept.trim();
  if (trimmed === 'all') return all;
  if (trimmed === 'high-only') return all.filter((p) => p.severity === 'high');
  const ids = new Set(
    trimmed
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean),
  );
  if (ids.size === 0) return { error: 'no IDs supplied' };
  const picked = all.filter((p) => ids.has(p.id));
  const found = new Set(picked.map((p) => p.id));
  const missing = [...ids].filter((id) => !found.has(id));
  if (missing.length > 0) return { error: `unknown proposal IDs: ${missing.join(', ')}` };
  return picked;
}

function ensureFeatureHeader(ticketDir: string, ticket: string): string {
  const explorePath = join(ticketDir, 'explore.feature');
  if (existsSync(explorePath)) return explorePath;

  // Synthesize a Feature header. Prefer copying from test.feature if present.
  const testFeaturePath = join(ticketDir, 'test.feature');
  let header: string;
  if (existsSync(testFeaturePath)) {
    const testContent = readFileSync(testFeaturePath, 'utf8');
    const firstFeatureMatch = testContent.match(/^Feature:.*$/m);
    header = firstFeatureMatch
      ? `${firstFeatureMatch[0]} (adversarial)\n  Adversarial scenarios beyond the acceptance criteria.\n  Generated by /xera-explore — review before merging into test.feature.\n\n`
      : `Feature: ${ticket} adversarial\n\n`;
  } else {
    header = `Feature: ${ticket} adversarial\n  Adversarial scenarios beyond the acceptance criteria.\n  Generated by /xera-explore — review before merging into test.feature.\n\n`;
  }
  writeFileSync(explorePath, header);
  return explorePath;
}

function formatScenario(p: Proposal): string {
  const tags = `@adversarial @adversarial-${p.category} @severity-${p.severity}`;
  const rationaleComment = `  # ${p.rationale}`;
  const indented = p.gherkin
    .split('\n')
    .map((line) => (line.startsWith('Scenario:') ? `  ${line}` : line ? `  ${line}` : line))
    .join('\n');
  return `\n  ${tags}\n${rationaleComment}\n${indented}\n`;
}

export async function exploreFinalizeCmd(argv: string[]): Promise<number> {
  const parsed = parseArgs(argv);
  if ('error' in parsed) {
    console.error(`[explore-finalize] ${parsed.error}`);
    return 1;
  }

  const cwd = process.cwd();
  const ticketDir = join(cwd, '.xera', parsed.ticket);
  const proposalsPath = join(ticketDir, 'adversarial-proposals.json');
  if (!existsSync(proposalsPath)) {
    console.error(
      `[explore-finalize] adversarial-proposals.json not found for ${parsed.ticket} — run /xera-explore Step 4 first`,
    );
    return 2;
  }

  let proposals: Proposals;
  try {
    const raw = JSON.parse(readFileSync(proposalsPath, 'utf8'));
    proposals = ProposalsSchema.parse(raw);
  } catch (e) {
    console.error(`[explore-finalize] invalid proposals JSON: ${(e as Error).message}`);
    return 1;
  }

  const picked = selectProposals(proposals.proposals, parsed.accept);
  if ('error' in picked) {
    console.error(`[explore-finalize] ${picked.error}`);
    return 1;
  }
  if (picked.length === 0) {
    console.error('[explore-finalize] no proposals matched the --accept filter');
    return 1;
  }

  const explorePath = ensureFeatureHeader(ticketDir, parsed.ticket);
  for (const p of picked) {
    appendFileSync(explorePath, formatScenario(p));
  }
  console.log(
    `[explore-finalize] appended ${picked.length} scenario(s) to ${explorePath} (${picked.map((p) => p.id).join(', ')})`,
  );
  return 0;
}
