export const AUTH_KEY_ENV = 'XERA_AUTH_KEY';

export function resolveAuthKey(): string {
  const key = process.env[AUTH_KEY_ENV];
  if (!key) {
    throw new Error(
      `${AUTH_KEY_ENV} not set. It is auto-generated by \`xera init\` and saved to .env. If you deleted .env, regenerate it by running \`xera init --update\` — note that any cached auth state will be invalidated.`,
    );
  }
  if (!/^[0-9a-f]{64}$/i.test(key)) {
    throw new Error(`${AUTH_KEY_ENV} must be a 64-character hex string (32 bytes).`);
  }
  return key;
}
